# Set your personal info.
# So that it can be display in your site.
author:
  # Optional, if not set, we will read author from hexo's _config.yml
  name:
  # Display your avatar
  avatar:
    # In theme or site directory (source/images): /images/avatar.gif
    # You can also use other linking images.
    url: /images/avatar.gif
    # If true, the avatar would be dispalyed in circle.
    rounded: true
    # If true, the avatar would be rotated with the cursor.
    rotated: false
  # Set your sns.
  # Example:
  # 1. set a sns link with name
  #   sns:
  #     - name: Twitter
  #       link: https://twitter.com/yourname
  # 2. set a sns link with a icon
  #   sns:
  #     - icon:
  #         name: github
  #         options: {type: 'fa'}
  #       link: https://twitter.com/yourname
  # 3. you can alse set both icon and name
  #   sns:
  #     - icon: {name: github, options: {type: 'fa'}}
  #       name: GitHub
  #       link: https://twitter.com/yourname
  sns:

# light or dark
color:
  default: light
  autodark: true

head:
  # Set web site favicon
  favicons:
  #  - rel: icon
  #    type: image/png
  #    sizes: 64x64
  #    href: /images/favicon-64.png
  #  - rel: icon
  #    type: image/png
  #    sizes: 128x128
  #    href: /images/favicon-128.png
  #  - rel: apple-touch-icon
  #    sizes: 180x180
  #    href: /images/favicon-180.png
  #  - rel: mask-icon
  #    color: red
  #    href: /images/favicon.svg
  # Header panel color.
  theme_color:
  # Set font.
  # These font family used in stylus
  # If you change them, please update stylus too.
  font: https://fonts.googleapis.com/css?family=Inconsolata|Itim|Lobster

footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  #since: 2019
  # Icon between year and copyright info.
  icon:
    name: heart
    options: {type: 'fa'}

post:
  # Meta display settings
  meta:
    item_text: false
    created_at: true
    updated_at:
      enable: false
      hide_same: true
    categories: true
  # Show previous post and next post in post footer if exists
  # Available values: left | right | false
  navigation: left
  # Creative Commons 4.0 International License.
  # See: https://creativecommons.org/share-your-work/licensing-types-examples
  # Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
  cc:

# sidebar menu
menu:
  home:
    enable: true # default is true
    path: /
    icon: {name: home, options: {type: 'fa'}}
    priority: 1 # default 10
  tags:
    enable: false
    path: /tags/
    icon: {name: tags, options: {type: 'fa'}}
    priority: 2
  categories:
    enable: false
    path: /categories/
    icon: {name: th, options: {type: 'fa'}}
    priority: 3
  archives:
    path: /archives/
    icon: {name: archive, options: {type: 'fa'}}
    priority: 5
  #commonweal:
  #  path: /404/
  #  icon: {name: heartbeat, options: {type: 'fa'}}

# Table Of Contents in the Sidebar
toc:
  enable: true
  # Automatically add list number to toc.
  number: true
  # If true, all words will placed on next lines if header width longer then sidebar width.
  wrap: false
  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: false
  # Maximum heading depth of generated toc. You can set it in one post through `toc_max_depth` in Front Matter.
  max_depth: 6

# Add #more for read more button.
jump_to_more: false

# TagCloud settings for tags page.
tagcloud:
  # If true, font size, font color and amount of tags can be customized
  enable: false
  # All values below are same as default, change them by yourself
  min: 12 # min font size in px
  max: 30 # max font size in px
  amount: 200 # amount of tags, chage it if you have more than 200 tags

# Comment Systems
# Available list: https://github.com/jiangtj/hexo-theme-cake/tree/master/lib/extend/comment
# You can defined comment, by set a Object
# Here is a disqus example
#   comment:
#     - name: disqus # require
#       button: # options, button content, if you use mutli-comment, it will be display
#       # name and button are defined by common handler, other config are defined by plugin self.
#       options:
#         shortname: your name
#       meta:
#         enable: true/false
comment:
