/**
 * Modify front-matter.
 *
 * Some keys are included by Hexo, please don't use them.
 * e.g. layout title date updated comments tags categories permalink keywords
 *
 * Some keys are generated by Hexo, don't use them either.
 * e.g. content excerpt more source full_source path permalink prev next raw photos link
 */

'use strict';

module.exports = hexo => {

  const keys = ['toc'];

  hexo.extend.filter.register('template_locals', locals => {
    const { page, theme } = locals;

    keys.forEach(key => {
      page[key] = Object.assign({}, theme[key], page[key]);
    });

    // Set default value for toc.max_depth
    if (!page.toc.max_depth) {
      page.toc.max_depth = 6;
    }
  });
};
