'use strict';

module.exports = hexo => {
  require('./filters/comment/default-config')(hexo);
  require('./filters/comment/disqus')(hexo);
  require('./filters/comment/livere')(hexo);
  require('./filters/head/font-awesome')(hexo);
  require('./filters/head/pace')(hexo);
  require('./filters/post-body-end/creative-commons')(hexo);
  require('./filters/post-body-end/reward')(hexo);
  require('./filters/post-body-end/tags')(hexo);
  require('./filters/front-matter')(hexo);
  require('./filters/lozad')(hexo);
  require('./filters/marked')(hexo);
  require('./filters/medium-zoom')(hexo);
  require('./helpers/cake-image')(hexo);
  require('./helpers/cake-title')(hexo);
  require('./helpers/canonical')(hexo);
  require('./helpers/favicon')(hexo);
  require('./helpers/next-config')(hexo);
  require('./helpers/next-js')(hexo);
  require('./helpers/next-url')(hexo);
  require('./helpers/post_nav')(hexo);
  require('./hexo/config')(hexo);
  require('./hexo/index')(hexo);
  require('./hexo/rm-filter')(hexo);
  require('./tags/bilibili')(hexo);
  require('./tags/button')(hexo);
  require('./tags/center-quote')(hexo);
  require('./tags/full-image')(hexo);
  require('./tags/group-pictures')(hexo);
  require('./tags/label')(hexo);
  require('./tags/note')(hexo);
  require('./tags/preview')(hexo);
  require('./tags/video')(hexo);
  require('./locals')(hexo);
};
