/* global hexo */
/**
 * Modify front-matter.
 *
 * Some key is included by hexo, please don't use it.
 * e.g. layout title date updated comments tags categories permalink keywords
 *
 * Some key is generated by hexo, don't use it too.
 * e.g. content excerpt more source full_source path permalink prev next raw photos link
 */

'use strict';

const keys = ['toc', 'reward_settings'];

hexo.extend.filter.register('template_locals', (locals) => {
  const { page, theme } = locals;
  keys.forEach(key => {
    page[key] = Object.assign({}, theme[key], page[key]);
  });
});
