name: 0x

on: [push]

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run 0x
      env:
        CODE_REF: ${{ github.ref }}
      run: |
        npm install hexo-cli -g --silent
        npm install 0x -g --silent
        npm install 0x -g --silent
        hexo init test
        cd test
        npm install
        git clone https://github.com/jiangtj-lab/hexo-many-posts.git --depth=1 --quiet source/_posts/skk

        hexo config theme cake
        npm install jiangtj/hexo-theme-cake#$CODE_REF --silent

        echo "- Generating flamegraph..."
        0x --output-dir 'dist' -- node ./node_modules/.bin/hexo g
        mv dist/flamegraph.html dist/index.html
    - name: Deploy Surge
      uses: yg/deploy-surge@v1
      with:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        DOMAIN_NAME: cake-0x.surge.sh
        BUILD_DIRECTORY: dist

